### ISSUE TITLE
Crash when "crafting" the stonecutter

### ISSUE THREAD

**Issue by jinkhya** [brckts/Portable-Stonecutter#8] opened 2021-01-16 21:50 UTC
Hello,
A player on our server threw ingredients and as soon as he used the anvil  to make the stonecutter it crashed : https://gist.github.com/jinkhya/80464433f011b850e721be9968af9d47

Modpack Enigmatica 6 (v 0.3.6)
Stone cutter 1.3.2
Forge 35.1.36
Thanks in advance.

**Comment by brckts** [comment] 2021-01-17 06:55
I can't seem to reproduce the issue, either on e6 or my dev instance. The crash seems to be related to the matching function, do you know what ingredients he had under the anvil ?

**Comment by jinkhya** [comment] 2021-01-17 14:55
I asked him, he said he threw a pressure plate (potentially spruce), 2 redstone and a stone cutter. I asked if he threw something else by mistake, he doesn't think so as far as he remembers.

**Comment by brckts** [comment] 2021-01-18 11:58
Still couldn't reproduce it on my end, I'll do some more investigation and get back to you if I get something. Does it happen every time you try crafting it on your server or did it just happen once ?

-------- Original Message --------

**Comment by brckts** [comment] 2021-02-27 15:24
closing this issue due to not being able to reproduce and no further information.

**Comment by Halfdeaf** [comment] 2021-02-27 23:42
I just got this same crash on the offical server. The player placed the pressure plate instead of throwing it on the ground.

**Comment by brckts** [comment] 2021-02-28 05:42
Got it, reopening that one I'll look into it in the morning. That information might actually allow me to replicate it this time.

**Comment by brckts** [comment] 2021-02-28 08:01
hmm, I still can't manage to crash my dev instance with the pressure plate placed.

this is the setup, right ?

![210228-0859-10](https://user-images.githubusercontent.com/51674867/109411592-1c806380-799b-11eb-8d9b-f85189c19baa.png)

**Comment by NielsPilgaard** [comment] 2021-02-28 09:02
Maybe it only happens on servers?

**Comment by brckts** [comment] 2021-02-28 09:03
I tried it on a server as well, maybe a mod interaction ? idk

**Comment by brckts** [comment] 2021-02-28 12:31
tried the same setup on a singleplayer e6 instance, didn't crash either, I added a few checks to the matching functions to prevent it from getting out of bounds. No idea if it fixed it since I still can't reproduce it.

**Comment by NielsPilgaard** [comment] 2021-02-28 19:27
I can't reproduce it either :/

**Comment by brckts** [comment] 2021-02-28 19:28
the mystery bug ! maybe by the next server crash we'll have more clues

**Comment by brckts** [comment] 2021-02-28 19:55
Finally managed to crash it, it happens when you put too much of one ingredient. Also confirmed that my fix works.

Releasing 1.3.4 as a hotfix.

**Closed as completed** 2021-02-28 19:58 UTC

**Comment by NielsPilgaard** [comment] 2021-02-28 20:39
I couldn't reproduce that either, but nice :P

**Comment by brckts** [comment] 2021-02-28 20:41
I managed to crash it by having the pressure plate placed, stonecutter thrown on it and too much redstone. I'll do some more digging in 1.3.3 tomorrow to see if it was really that, you're making me doubt :p

-------- Original Message --------
